### ISSUE TITLE
Defining of Blocks

### ISSUE THREAD

**Issue by MKleinSB** [CalliTGS3/pxt-calliope-sharpGP2Y1010AU0F#1]
Shouldn´t the blocks look better like this at line 25? 
   
//% blockId="initDustSensor" block="initialize dustsensor with DigitalPin %vled | AnalogPin %vo| and Samples %samples"
    //% vled.defl=DigitalPin.P3
    //% vo.defl=AnalogPin.P2
    //% samples.defl=10
    export function initDustSensor(vled: DigitalPin, vo: AnalogPin, samples: number) {

**Comment by CalliTGS3** [comment]
Changed. Thank you for suggestion. 
Guess we can we change to German language? 
Wir können uns sicher mal ausserhalb der issues austauschen.

**Comment by MKleinSB** [comment]
Ja, gerne auch unter amigafreak (at) web.de
